# Generated by Django 6.0.7 on 2026-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('categorie', models.CharField(choices=[('Concours académique', 'Concours académique'), ('Compétition sportive', 'Compétition sportive'), ('Atelier / Formation', 'Atelier / Formation'), ('Conférence', 'Conférence')], max_length=50, verbose_name='Catégorie')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement Mobile Money')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation / message')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('place', models.CharField(editable=False, max_length=10)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
